version: "3"
services:
  server:
    build: ./server
    ports:
      - "8080:8080"
    container_name: dictionary-map-server
  client:
    build: ./client
    ports:
      - "4200:80"
    container_name: dictionary-map-client